# Generated by Django 5.0.3 on 2024-03-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
